spring:
  application:
    name: parking-management-api
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_management
    driver-class-name: org.postgresql.Driver
    username: parking_user
    password: parking_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10

jwt:
  secret: your-secret-key-here-make-it-long-and-secure-in-production
  expiration: 86400000 # 1 día en milisegundos
  refresh:
    expiration: 86400000 # 1 dia en milisegundos

# Redis configuration
redis:
  host: localhost
  port: 6379
  database: 0
  password: parking_password
  timeout: 2000

# Logging configuration for development

logging:
  level:
    ar.edu.itba.parkingmanagmentapi: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    org.springframework.data.redis.core: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


recovery:
  expose-token-in-response: true
