# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ParkingManagementMobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Permissions (Uncomment when configuring permissions)
  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  # Firebase (Uncomment when configuring Firebase)
  # pod 'Firebase/Core'
  # pod 'Firebase/Messaging'

  # Maps (Uncomment when configuring Maps)
  # pod 'react-native-google-maps', path: '../node_modules/react-native-maps'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
